### ISSUE TITLE
Make this a Swift Package

### ISSUE THREAD

**Issue by KyNorthstar** [LithoByte/funnet#11]
All of my personal and my company's Apple-platform apps consume dependencies via Swift Package rather than CocoaPods, but I want to use this because it seems to be very well-made. It shouldn't be too much effort to convert this to a Swift package.

**Comment by schrockblock** [comment]
Thank you so much @KyLeggiero! That's very kind of you to say, we appreciate it very much.

Just wanted to give you an update – this has been assigned, and we're currently working on getting the dependencies moved to SPM so this can be easily switched over as well. We have some client work happening as well, but target is end of next week to fully support SPM on this library.

Thanks again, and we'll keep you updated!

**Comment by schrockblock** [comment]
@KyLeggiero let us know how this works for you! This is one of the more complicated SPM conversions we've done (simply due to the interdependencies) so feel free to open other issues if you have trouble with any given product.

**Comment by KyNorthstar** [comment]
@schrockblock sorry; I've been removed from the project I was on which used this. Good luck testing out the fix and thank you for your hard work!
